### ISSUE TITLE
Release v0.2.0 Pinhead

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga-legacy#38]
### v0.2.0 Pinhead

![pinhead](https://static.comicvine.com/uploads/original/12/123441/3246521-pinhead_wallpaper_by_evilflesh.jpg)

### Marketing/Social
- [ ] #10 Liar a la gente y birras pagadas

### Features
- [ ] #80 Implementación de Router y Plantillas
- [ ] #67 Marca de agua
- [ ] #47 Login con Github usando Firebase
- [ ] #51 Perfil del usuario
- [ ] #49 Gestión de multimedia
- [ ] #50 Link del Meme generado
- [ ] #45 Compartir en redes sociales... 
- [ ] #46 Migración de los templates de MEMES
- [ ] #44 Lazy loading para los memes de la galeria
- [ ] #48 Newsletter con Mailchimp

### Bugs
- [ ] #42 Refactorizar Javascript
- [ ] #78 Code style...

### Review
- [ ] Calidad del código
- [ ] Test :trollface:
